- hosts: localhost
  become: yes
  vars:
    file_path: /home/devops/ansible_implementation
    file_and_password:
      vault-pass: redhat 
      vault-pass-change: ansible 
  tasks:
  - name: Create Directory
    file: 
      path: ~devops/ansible_implementation
      state: directory
      mode: 0755  
      owner: devops
      group: devops

  - name: Create file
    copy:
      content: |
        This is encrypted.
        This is also encrypted.
      dest: ~devops/ansible_implementation/{{ item }}
      mode: 0644  
      owner: devops
      group: devops 
    loop: 
      - super-secret.yml
      - super-secret-decrypted.yml

  - name: Create Password file1
    copy:
      content: "{{ item.value }}"
      dest: ~devops/ansible_implementation/{{ item.key }}
      mode: 0600  
      owner: devops
      group: devops 
    loop: "{{ file_and_password |dict2items }}"

  - name: Encrypt file by ansible-vault
    shell:  ansible-vault encrypt /home/devops/ansible_implementation/super-secret.yml --vault-password-file=/home/devops/ansible_implementation/vault-pass-change
    become: yes

  - name: Encrypt file by ansible-vault
    shell:  ansible-vault encrypt /home/devops/ansible_implementation/super-secret-decrypted.yml --output=/home/devops/ansible_implementation/super-secret-encrypted.yml --vault-password-file=/home/devops/ansible_implementation/vault-pass
    become: yes

  - name: Create secret variable file
    copy:
      content: |
        newusers:
          - name: ansibleuser1
            pw: redhat
          - name: ansibleuser2
            pw: Re4H1T  
      dest: "{{file_path}}/secret.yml" 
      mode: 0644  
      owner: devops
      group: devops   

  - name: Encrypt secret variable by ansible-vault
    shell: ansible-vault encrypt "{{file_path}}/secret.yml" --vault-password-file="{{file_path}}/vault-pass"
    become: yes

  - name: Create secret variable file
    copy:
      src: create_users.yml  
      dest: "{{file_path}}/create_users.yml" 
      mode: 0644  
      owner: devops
      group: devops

  - name: Create secret variable file
    copy:
      content: |
          [lb]
          frontend1.{{GUID}}.internal

          [webservers]
          app1.{{GUID}}.internal
          app2.{{GUID}}.internal

          [db]
          appdb1.{{GUID}}.internal
      dest: "{{file_path}}/hosts" 
      mode: 0644  
      owner: devops
      group: devops

  - name: Execute Playbook
    shell: ansible-playbook -i "{{file_path}}/hosts"  "{{file_path}}/create_users.yml"  --vault-password-file="{{file_path}}/vault-pass" -vvv

